/*
 * API Emissão server
 *
 * API para integração da paySmart com emissor para consulta e consumo de saldo e/ou limite para cartões. Esta especificação descreve os serviços que serão consumidos pela paySmart em uma API cuja implementação é de responsabilidade do emissor. As funções serão chamadas na sequência da interação entre a bandeira e paySmart no fluxo de pagamentos, após serem realizadas todas as validações de segurança por parte da bandeira e da processadora respectivamente.<p><strong>Tempos de resposta:</strong></p><ul><li><strong>< 2 segundos: Ideal</strong></li><li><strong>2 a 4 segundos: Começa a gerar alarmes</strong></li><li><strong>4 a 7 segundos: Baixa probabilidade de autorização</strong></li><li><strong>> 7 segundos: Timeout</strong></li></ul>
 *
 * API version: v1-oas3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// PaymentType : Tipo de Pagamento. Este campo deve conter um dos seguintes itens. * A2A = conta para conta * B2A = banco para conta * P2P = pessoa para pessoa * CSB = Cashback * DSB = Desembolso
type PaymentType string

// List of PaymentType
const (
	A2_A PaymentType = "A2A"
	B2_A PaymentType = "B2A"
	P2_P PaymentType = "P2P"
	CSB  PaymentType = "CSB"
	DSB  PaymentType = "DSB"
)
