/*
 * API Emissão server
 *
 * API para integração da paySmart com emissor para consulta e consumo de saldo e/ou limite para cartões. Esta especificação descreve os serviços que serão consumidos pela paySmart em uma API cuja implementação é de responsabilidade do emissor. As funções serão chamadas na sequência da interação entre a bandeira e paySmart no fluxo de pagamentos, após serem realizadas todas as validações de segurança por parte da bandeira e da processadora respectivamente.<p><strong>Tempos de resposta:</strong></p><ul><li><strong>< 2 segundos: Ideal</strong></li><li><strong>2 a 4 segundos: Começa a gerar alarmes</strong></li><li><strong>4 a 7 segundos: Baixa probabilidade de autorização</strong></li><li><strong>> 7 segundos: Timeout</strong></li></ul>
 *
 * API version: v1-oas3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type WithdrawalQuery struct {
	// Identificador interno.
	WithdrawalQueryId string `json:"withdrawal_query_id"`
	// Identificador interno da conta
	AccountId string `json:"account_id"`
	// Código do produto. Este código é fornecido pela paySmart para o emissor.
	PsProductCode string `json:"psProductCode"`
	// Nome do produto. Este nome é fornecido pela paySmart para o emissor.
	PsProductName string `json:"psProductName,omitempty"`
	// Tipo do produto. Este indica se o produto é pré-pago ou pós-pago.
	ProductType string `json:"productType,omitempty"`
	// Código do país conforme ISO 3166-1.
	CountryCode string `json:"countryCode"`

	Source *Source `json:"source"`
	// Nome/identificador do serviço que fez essa chamada. Geralmente autorizador-8583.
	CallingSystemName string `json:"callingSystemName"`

	Authorization *Authorization `json:"authorization"`

	Brand *Brand `json:"brand"`

	Card *Card `json:"card"`

	EntryMode *EntryMode `json:"entry_mode"`

	ProcessingCode *ProcessingCode `json:"processing_code"`
	// Indica se a transação é internacional (true) ou nacional (false)
	Internacional bool `json:"internacional"`

	OriginalIso8583 *Iso8583Message `json:"original_iso8583"`
	// O ID de Referência da Bandeira (NRID) é um ID numérico único gerado pela bandeira e que permanece sem alteração ao longo da vida da transação.
	Nrid string `json:"nrid,omitempty"`

	AdditionalTerminalData *AdditionalTerminalData `json:"additionalTerminalData,omitempty"`

	TokenPaymentData *TokenPaymentData `json:"tokenPaymentData,omitempty"`
	// Indica se é uma transação feita com cartão HCE (true) ou outro tipo de cartão (false)
	HceTransaction bool `json:"hceTransaction,omitempty"`
}
