/*
 * API Emissão server
 *
 * API para integração da paySmart com emissor para consulta e consumo de saldo e/ou limite para cartões. Esta especificação descreve os serviços que serão consumidos pela paySmart em uma API cuja implementação é de responsabilidade do emissor. As funções serão chamadas na sequência da interação entre a bandeira e paySmart no fluxo de pagamentos, após serem realizadas todas as validações de segurança por parte da bandeira e da processadora respectivamente.<p><strong>Tempos de resposta:</strong></p><ul><li><strong>< 2 segundos: Ideal</strong></li><li><strong>2 a 4 segundos: Começa a gerar alarmes</strong></li><li><strong>4 a 7 segundos: Baixa probabilidade de autorização</strong></li><li><strong>> 7 segundos: Timeout</strong></li></ul>
 *
 * API version: v1-oas3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type Withdrawal struct {
	// Identificador interno do saque
	WithdrawalId string `json:"withdrawal_id"`
	// Identificador interno da conta
	AccountId string `json:"account_id"`
	// Código do produto. Este código é fornecido pela paySmart para o emissor.
	PsProductCode string `json:"psProductCode"`
	// Nome do produto. Este nome é fornecido pela paySmart para o emissor.
	PsProductName string `json:"psProductName,omitempty"`
	// Tipo do produto. Este indica se o produto é pré-pago ou pós-pago.
	ProductType string `json:"productType,omitempty"`
	// Código do país conforme ISO 3166-1.
	CountryCode string `json:"countryCode"`

	Source *Source `json:"source"`
	// Nome/identificador do serviço que fez essa chamada. Geralmente autorizador-8583.
	CallingSystemName string `json:"callingSystemName"`

	Authorization *Authorization `json:"authorization"`

	Brand *Brand `json:"brand"`

	Card *Card `json:"card"`

	TotalAmount *Amount `json:"total_amount"`

	DollarAmount *Amount `json:"dollar_amount,omitempty"`

	OriginalAmount *Amount `json:"original_amount"`
	// Cotação para conversão de câmbio Dólar -> Real
	DollarRealRate string `json:"dollar_real_rate,omitempty"`
	// Spread (ou markup) aplicado em transações internacionais
	Spread string `json:"spread,omitempty"`

	EntryMode *EntryMode `json:"entry_mode"`

	ProcessingCode *ProcessingCode `json:"processing_code"`

	HolderValidationMode *HolderValidationMode `json:"holder_validation_mode,omitempty"`

	Fees []Fee `json:"fees"`

	Establishment *Establishment `json:"establishment"`
	// Indica se a transação é internacional (true) ou nacional (false)
	Internacional bool `json:"internacional"`

	OriginalIso8583 *Iso8583Message `json:"original_iso8583"`

	FraudData *FraudData `json:"fraudData,omitempty"`
	// O ID de Referência da Bandeira (NRID) é um ID numérico único gerado pela bandeira e que permanece sem alteração ao longo da vida da transação.
	Nrid string `json:"nrid,omitempty"`
	// Força que a transação seja aceita, mesmo que não tenha saldo suficiente ou algo do tipo.
	ForceAccept bool `json:"forceAccept,omitempty"`
	// Indica se este saque é um aviso de autorização de saque (true) ou é uma requisição de saque que deve ser validada pelo emissor (false ou não informado). Avisos de autorização devem ser aceitos pelo emissor, pois já foram aprovados pelo sistema de Stand-In da bandeira ou processadora mediante parâmetros informados pelo emissor no sistema de Stand-In.
	AuthorizationAdvice bool `json:"authorizationAdvice,omitempty"`

	AdditionalTerminalData *AdditionalTerminalData `json:"additionalTerminalData,omitempty"`

	TokenPaymentData *TokenPaymentData `json:"tokenPaymentData,omitempty"`
	// Indica se é uma transação feita com cartão HCE (true) ou outro tipo de cartão (false)
	HceTransaction bool `json:"hceTransaction,omitempty"`
}
