/*
 * API Emissão server
 *
 * API para integração da paySmart com emissor para consulta e consumo de saldo e/ou limite para cartões. Esta especificação descreve os serviços que serão consumidos pela paySmart em uma API cuja implementação é de responsabilidade do emissor. As funções serão chamadas na sequência da interação entre a bandeira e paySmart no fluxo de pagamentos, após serem realizadas todas as validações de segurança por parte da bandeira e da processadora respectivamente.<p><strong>Tempos de resposta:</strong></p><ul><li><strong>< 2 segundos: Ideal</strong></li><li><strong>2 a 4 segundos: Começa a gerar alarmes</strong></li><li><strong>4 a 7 segundos: Baixa probabilidade de autorização</strong></li><li><strong>> 7 segundos: Timeout</strong></li></ul>
 *
 * API version: v1-oas3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type TransferData struct {
	PaymentType *PaymentType `json:"paymentType"`
	// Número Único de referência. Número de Referência atribuído pelo Originador da Transferência de Fundos (Gateway). Preenchimento - Conteúdo alfanumérico, espaços a direita se necessário. Para transação doméstica, caso o tipo de pagamento seja igual a P2P e os cartões do remetente e do destinatário forem da bandeira Elo, o conteúdo deste campo deverá ser o mesmo nas transações de retirada de fundos e de recebimento de fundos.
	UniqueReferenceNumber string `json:"uniqueReferenceNumber,omitempty"`
	// Nome do Remetente. Nome de quem está enviando os fundos na transferência. Transação de recebimento de fundos e retirada de fundos - Enviado se capturado pelo gateway.
	SendersName string `json:"sendersName,omitempty"`
	// Endereço do Remetente. Endereço de quem está enviando os fundos na transferência. Campo Mandatório em transações internacionais. Opcional em transações domésticas.
	SendersAddress string `json:"sendersAddress,omitempty"`
	// Cidade do Remetente. Cidade de quem está enviando os fundos na transferência. Campo Mandatório em transações internacionais. Opcional em transações domésticas.
	SendersCity string `json:"sendersCity,omitempty"`
	// Código do País ou código estado se o país for os Estados Unidos. Código do País de quem está enviando os fundos na transferência. Se o país for Estados Unidos deve ser enviado o código do estado e não o do país. Esta informação deve ser enviada em todas as transações utilizando como base a ISO 3166-1 numeric. Para transações nacionais utiliza-se o código 076 (Brasil). Campo Mandatório em transações internacionais. Opcional em transações domésticas.
	CountryOrStateCodeIfUS string `json:"countryOrStateCodeIfUS,omitempty"`
	// CEP do Portador. CEP de quem está retirando ou recebendo os fundos na transferência. Na transação de retirada de fundos - Campo refere-se ao Destinatário. Na transação de recebimento de fundos - Campo refere-se ao Remetente. Campo Mandatório em transações internacionais exceto na retirada de fundos. Campo Opcional em transações domésticas.
	CardholderZipcode string `json:"cardholderZipcode,omitempty"`
	// Número de identificação do portador impactado com esta transação. No caso de transações internacionais, o conteúdo deste campo deve corresponder a um Número único designado e enviado pelo originador da transação (Gateway). Não deve ser o PAN. No caso de domésticas, o conteúdo deste campo deve corresponder ao CPF / CNPJ do portador que está recebendo os fundos da transferência no caso de transação de retirada de fundos e ao CPF / CNPJ do portador que está enviando os fundos da transferência no caso de transação de recebimento de fundos. Neste caso, a formatação do campo para transação doméstica seguirá o seguinte formato. Posições de 0 a 14 Na transação de retirada de fundos, preencher com o Número do CPF ou CNPJ do Destinatário, completando com zeros a esquerda se necessário. Na transação de recebimento de fundos preencher com o Número do CPF ou CNPJ do Remetente, completando com zeros a esquerda se necessário.
	CardholderIdentificationNumber string `json:"cardholderIdentificationNumber,omitempty"`
	// Origem dos fundos. A origem dos fundos que o remetente está utilizando. Valores válidos incluem * 01 = Crédito * 02 = Débito * 03 = Pré pago * 04 = Dinheiro * 05 = Cheque * 06 = ACH/FED * 07-16 = Reservado para Uso Futuro * 17 = Conta Corrente * 18 = Conta Poupança * 19 = Outro  Campo Mandatório quando tipo de pagamento for igual a \"P2P\", \"A2A\" ou \"B2A\" e opcional para os demais.
	OriginOfFunds string `json:"originOfFunds,omitempty"`
	// Data de Nascimento do remetente. O formato deve ser MMDDAAAA.
	BirthDateOfSender string `json:"birthDateOfSender,omitempty"`
	// Nome do destinatário. Nome de quem está recebendo os fundos da transferência (recebedor). Enviado se capturado pelo gateway.
	RecipientsName string `json:"recipientsName,omitempty"`
	// Dados Adicionais da Transferência. Exclusivamente para transações domésticas. Carrega dados complementares para transações de transferência de fundos. O conteúdo das informações deste elemento é livre e estabelecido pelo próprio Gateway.
	AdditionalTransferData string `json:"additionalTransferData,omitempty"`
	// Código do Destinatário. Exclusivamente para transações domésticas. Apresenta o código do Destinatário constante no Diretório do Gateway (código do recebedor).
	RecipientCode string `json:"recipientCode,omitempty"`
	// E-mail do Remetente dos fundos. Exclusivamente para transações domésticas, sendo enviado se capturado pelo gateway. Esta Tag é de uso exclusivo para o Tipo de pagamento P2P.
	FundSenderEmail string `json:"fundSenderEmail,omitempty"`
	// E-mail do Destinatário dos fundos. Exclusivamente para transações domésticas, sendo enviado se capturado pelo gateway. Esta Tag é de uso exclusivo para os Tipos de pagamento P2P, CSB e DSB.
	FundRecipientEmail string `json:"fundRecipientEmail,omitempty"`
	// Telefone do Remetente dos fundos. Exclusivamente para transações domésticas, sendo enviado se capturado pelo gateway. Esta Tag é de uso exclusivo para o Tipo de pagamento P2P.
	FundSenderPhone string `json:"fundSenderPhone,omitempty"`
	// Telefone do Destinatário dos fundos. Exclusivamente para transações domésticas, sendo enviado se capturado pelo gateway. Esta Tag é de uso exclusivo para os Tipos de pagamento P2P, CSB e DSB.
	FundRecipientPhone string `json:"fundRecipientPhone,omitempty"`
	// Device ID. Exclusivamente para transações domésticas, onde este campo deve ser enviado com o conteúdo que identifica de forma única o dispositivo que originou a transação de retirada ou recebimento de fundos. Esta Tag deve ser enviada para o Tipo de pagamento P2P se capturada pelo gateway. Esta Tag é opcional para os Tipos de pagamento DSB e CSB.
	DeviceID string `json:"deviceID,omitempty"`
	// CPF/CNPJ do Portador do cartão desta transação. Exclusivamente para transações domésticas, onde este campo deve ser enviado se a informação for capturada pelo gateway. Dado que identifica o CPF / CNPJ do portador do cartão desta transação. Para transação de retirada de fundos, deverá ser considerado o CPF / CNPJ do remetente dos fundos da transferência. Para transação de recebimento de fundos, deverá ser considerado o CPF / CNPJ do destinatário dos fundos da transferência. Completar com zeros a esquerda se necessário.
	CardholderCpfOrCnpj string `json:"cardholderCpfOrCnpj,omitempty"`
	// BIN Retirada. Exclusivamente para transações domésticas de recebimento de fundos, onde este campo é mandatório se a origem dos fundos for uma conta cartão. Esta Tag é de uso exclusivo para o Tipo de pagamento P2P.
	BINOrigin string `json:"BINOrigin,omitempty"`
	// BIN Destino. Exclusivamente para transações domésticas de retirada de fundos, onde este campo é mandatório se o destino dos fundos for uma conta cartão. Esta Tag é de uso exclusivo para o Tipo de pagamento P2P.
	BINDestination string `json:"BINDestination,omitempty"`
	// 4 últimos dígitos do cartão da retirada de fundos. Exclusivamente para transações domésticas de recebimento de fundos, onde este campo é mandatório se a origem dos fundos for uma conta cartão. Esta Tag é de uso exclusivo para o Tipo de pagamento P2P.
	OriginCardLast4digits string `json:"originCardLast4digits,omitempty"`
	// 4 últimos dígitos do cartão de destino dos fundos. Exclusivamente para transações domésticas de retirada de fundos, onde este campo é mandatório se o destino dos fundos for uma conta cartão. Esta Tag é de uso exclusivo para o Tipo de pagamento P2P (Tag 01).
	DestinationCardLast4digits string `json:"destinationCardLast4digits,omitempty"`
}
